### ISSUE TITLE
chartjs-to-image in React through a button click

### ISSUE THREAD

**Issue by tamojay-dey** [typpo/chartjs-to-image#13]
I want to have a button in my chart header which will save the screenshot of my chartjs on click. Is there any way to do that using chartjs-to-image?

**Comment by typpo** [comment]
This is certainly possible, but the implementation is not specific to this library.  You can absolute position a button over your chart and have it do anything on click.

chartjs-to-image can be used to do this, but because your use case sounds entirely user-facing you're probably better off using the `toBase64Image` function built into Chart.js https://quickchart.io/documentation/chart-js/image-export/#use-tobase64image()-in-the-browser
